str1='acc213'
str2='123'
str3='asdasd'
str4='_asd'
print(str1.isalnum())
print(str1.isalpha())
print(str1.isdigit())
print('---------------------1')
print(str2.isalnum())
print(str2.isalpha())
print(str2.isdigit())
print('---------------------2')
print(str3.isalnum())
print(str3.isalpha())
print(str3.isdigit())
print('---------------------3')
print(str1.isidentifier())
print(str2.isidentifier())
print(str3.isidentifier())
print(str4.isidentifier())
print('---------------------4')
str5='Yrwew'
print(str5.isupper())
print(str5.islower())
print('---------------------5')
str6=" "
print(str6.isspace())
str7='\t'
print(str7.isspace())
str8="\n"
print(str8.isspace())
str9="\b"
print(str9.isspace())
print('---------------------6')
print(str5.startswith('Y'))
print(str5.startswith('y'))
str10='ddd.py'
print(str10.endswith('.py'))